# Generated by Django 4.2.28 on 2026-02-11 16:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The official name of the organization.",
                        max_length=512,
                        verbose_name="Name",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("legislature", "Legislature"),
                            ("executive", "Executive Body"),
                            ("judiciary", "Judiciary"),
                            ("party", "Political Party"),
                            ("ministry", "Ministry"),
                            ("committee", "Committee"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        help_text="The category of the organization (e.g., Legislature, Party).",
                        max_length=50,
                        verbose_name="Classification",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-3 code (e.g., NGA, ZAF, KEN).",
                        max_length=3,
                        verbose_name="Country Code",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization that contains this one (e.g., a committee within a parliament).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="registry.organization",
                        verbose_name="Parent Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The primary name the person is known by.",
                        max_length=512,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "biography",
                    models.TextField(
                        blank=True,
                        help_text="A short biography or description of the person.",
                        null=True,
                        verbose_name="Biography",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "death_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Death"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Male, Female, etc.",
                        max_length=50,
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Summary / One-liner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "label",
                    models.CharField(
                        help_text="The name of the office (e.g., 'Senator for Lagos West').",
                        max_length=512,
                        verbose_name="Label",
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("legislative", "Legislative"),
                            ("executive", "Executive"),
                            ("judicial", "Judicial"),
                            ("local_government", "Local Government"),
                            ("traditional_authority", "Traditional Authority"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        help_text="The branch of government or type of authority.",
                        max_length=50,
                        verbose_name="Role Type",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The body where this post exists (e.g., The Senate).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="registry.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="The date the person took office.",
                        null=True,
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="The date the person left office.",
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                (
                    "selection_method",
                    models.CharField(
                        choices=[
                            ("elected", "Elected"),
                            ("appointed", "Appointed"),
                            ("ex_officio", "Ex Officio"),
                            ("hereditary", "Hereditary"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        help_text="How the person obtained this position (e.g., elected vs appointed).",
                        max_length=50,
                        verbose_name="Selection Method",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization the person belongs to (e.g., The Parliament).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="registry.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        help_text="The political party the person belonged to during this specific membership.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="party_memberships",
                        to="registry.organization",
                        verbose_name="Party Affiliation",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="registry.person",
                        verbose_name="Person",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific post held (e.g., 'MP for Lagos West'). Optional if generic membership.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships",
                        to="registry.post",
                        verbose_name="Post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "ordering": ["-start_date"],
            },
        ),
    ]
